
Vagrant.configure("2") do |config|
  config.vm.box = "debian-sandbox/bookworm64"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.network "forwarded_port", guest: 22, host: 2200
  config.ssh.port = "2200"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
end
